#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

defined('YII_ENV') or define('YII_ENV', 'prod');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/config/bootstrap.php';

$config = require __DIR__ . '/config/main.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
